### ISSUE TITLE
Timing:  58½ instead of 58 seconds

### ISSUE THREAD

**Issue by patrickbucher** [manuelmeister/Swiss-Railway-Clock#1]
It seems that the second indicator rotates once every 58 seconds:

```javascript
function set_First_CSS_Second_Animation() {
    $('#seconds-container').css({
        '-webkit-animation': 'rotate-' + seconds + ' ' + (58 - seconds) + 's linear',
        'animation': 'rotate-' + seconds + ' ' + (58 - seconds) + 's linear'
    });
}
```

The real SBB clock uses a timing of 58½ seconds [source](https://news.sbb.ch/artikel/82722/der-zeit-voraus).

**Comment by manuelmeister** [comment]
Thank you, I changed it, so it uses 58.5 s for a full rotation. (FYI: the current implementation does not allow me to define 58.5 seconds for the first pass. But from then on, it uses the 58.5 seconds.)
If you have an idea to improve the design you can create a pull request.
